services:
  postgres:
    container_name: food
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: food
    volumes:
      - ./data/pg:/data/postgres
